# Auto-generated by keel-lang/keel release workflow on tag v0.1.10.
# Install: brew install keel-lang/tap/keel
#
# Supported platforms: macOS (Apple Silicon) and Linux x86_64.
# Intel Macs can build from source via .
class Keel < Formula
  desc "A programming language where AI agents are first-class citizens (alpha)"
  homepage "https://keel-lang.dev"
  license "MIT"
  version "0.1.10"

  on_macos do
    on_arm do
      url "https://github.com/keel-lang/keel/releases/download/v0.1.10/keel-aarch64-apple-darwin.tar.gz"
      sha256 "55e1b125ca975fae8ba5e266557dd7ac78225333d07fb152201325a11191c881"
    end
    # Intel Macs: build from source — no prebuilt binary.
  end

  on_linux do
    url "https://github.com/keel-lang/keel/releases/download/v0.1.10/keel-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "89a1ccfe66e81aabc063c6e7ac631a71cd19925edae848da48e01a9acd2947a1"
  end

  def install
    bin.install "keel"
  end

  test do
    system "#{bin}/keel", "--version"
  end
end
