# Auto-generated by keel-lang/keel release workflow on tag v0.1.18.
# Install: brew install keel-lang/tap/keel
#
# Supported platforms: macOS (Apple Silicon) and Linux x86_64.
# Intel Macs can build from source via .
class Keel < Formula
  desc "A programming language where AI agents are first-class citizens (alpha)"
  homepage "https://keel-lang.dev"
  license "MIT"
  version "0.1.18"

  on_macos do
    on_arm do
      url "https://github.com/keel-lang/keel/releases/download/v0.1.18/keel-aarch64-apple-darwin.tar.gz"
      sha256 "972dc54c804d07725a4ca7b7badaa435f1f620468f9e04f1e99934bcd1e8cf60"
    end
    # Intel Macs: build from source — no prebuilt binary.
  end

  on_linux do
    url "https://github.com/keel-lang/keel/releases/download/v0.1.18/keel-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "dae11c3c36b0864eb06974f30ab389140f9915125c8fda1fc1bc22fb715fa253"
  end

  def install
    bin.install "keel"
  end

  test do
    system "#{bin}/keel", "--version"
  end
end
