# Auto-generated by keel-lang/keel release workflow on tag v0.1.13.
# Install: brew install keel-lang/tap/keel
#
# Supported platforms: macOS (Apple Silicon) and Linux x86_64.
# Intel Macs can build from source via .
class Keel < Formula
  desc "A programming language where AI agents are first-class citizens (alpha)"
  homepage "https://keel-lang.dev"
  license "MIT"
  version "0.1.13"

  on_macos do
    on_arm do
      url "https://github.com/keel-lang/keel/releases/download/v0.1.13/keel-aarch64-apple-darwin.tar.gz"
      sha256 "a8d1b34fb34ad3c5288c4794e182c0d9d19708fb2fca7d3a0b33bfa38dff9e43"
    end
    # Intel Macs: build from source — no prebuilt binary.
  end

  on_linux do
    url "https://github.com/keel-lang/keel/releases/download/v0.1.13/keel-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "957eeb5015ba08adf72d31ba926647f3300cbc1ac341a19e6d2a945a7812eda4"
  end

  def install
    bin.install "keel"
  end

  test do
    system "#{bin}/keel", "--version"
  end
end
